spring:
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 1GB
  application:
    name: snow-cloud-drive
  thymeleaf:
    cache: false
  datasource:
    url: jdbc:mysql://localhost:3307/snow_cloud_drive?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: zfmx
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8111
SnowCloudDrive:
  file:
    path: D:\project\SnowCloudDrive\files