spring:
  application:
    name: snow-cloud-drive
  thymeleaf:
    cache: false
  datasource:
    url: jdbc:mysql://localhost:3307/snow_cloud_drive?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8111
  servlet:
    session:
      persistent: false
